import Navbar from "@/components/Navbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-950 text-gray-200 min-h-full`}
      >
        <Navbar />
        <main className="container mx-auto px-4 py-9">
          <Toaster position="top-center" />
          {children}

        </main>
      </body>
    </html>
  );
}
